import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import Player from '../components/player'
import styles from '../styles/Home.module.css'

const ar = [1, 2, 3, 4, 5, 6]

export default function Home() {
  const [data, setData] = useState([])
  const [current, setCurrent] = useState([0])
  const [order, setOrder] = useState([0, 1, 2, 3, 4, 5])
  useEffect(() => {
    let formattedAr = []
    for (let i = 0; i < ar.length; i++) {
      formattedAr.push({
        value: ar[i],
        order: i
      })
    }
    console.log(formattedAr)
    setData(formattedAr)
  }, [])

  const delay = (j, del) => {
    setData((state) => {
      console.log(j)
      if (state[j].value > state[j + 1].value) {
        var tempAr = [...state]
        var temp = { ...tempAr[j].order };
        tempAr[j] = { ...tempAr[j + 1] };
        tempAr[j + 1] = temp;
        tempAr[j].order = j
        tempAr[j + 1].order = j + 1
        return tempAr
      } return state

    })
    setCurrent(j)
    return new Promise((resolve, reject) => setTimeout(() => resolve(j), 1500));
  }

  const sort = async () => {
    setOrder([1,0,2,3,4,5])
    return
    for (var i = 0; i < data.length; i++) {
      for (var j = 0; j < (data.length - i - 1); j++) {
        await delay(j)
      }
    }

  }
  useEffect(() => {
    // console.log("CHANGED", data)
  }, [data])

  return (
    <div style={{}}>
      {/* <Head>
        <title>Study lo fi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      {/* <main className='media_container'>
        <img src='/media/1.gif' />
        <div className='crt-lines' />
        <div className='ytplayer'>
          <Player />
        </div>
      </main> */}
      <button onClick={sort}>SORT</button>
      <div style={{ display: 'flex', width: '100%', border: '1px solid green',minHeight:'100px', flexDirection: 'row', position: 'absolute', bottom: '0px', alignItems: 'flex-end', bottom: '50px' }}>
        {data.map((bar, index) => {
          // console.log('building')
          return (
            <div key={index} style={{
              border: '1px solid red',
              position:'absolute',
              left: `${order[index ] * 20}px`,
              width: '20px',
              minHeight: `${bar.value * 20}px`,
              transition: 'all linear 1000ms'
            }}>
              {bar.value}
            </div>
          )
        })}
      </div>

      <div style={{ position: 'absolute', bgcolor: 'red', display: 'flex', border: '3px solid green', bottom: '40px', minWidth: '38px', left: `${current * 20}px` }}></div>




    </div>
  )
}
